require("priyanshu.core.options")
require("priyanshu.core.keymaps")
require("priyanshu.core.autocommands")
require("priyanshu.core.extras.cwd-persistent")
require("priyanshu.core.extras.quickfix")
require("priyanshu.core.extras.session")
require("priyanshu.core.extras.vim-log")
